name: flutter_platform_lz4
description: Block LZ4 decompressing for Android and iOS using platform-specific code.
version: 0.0.1
homepage: https://github.com/AegisDevBR

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.dev.aegis.flutter_platform_lz4
        pluginClass: FlutterPlatformLz4Plugin
      ios:
        pluginClass: FlutterPlatformLz4Plugin
